create table authority(
    id int PRIMARY KEY generated by default as identity,
    name varchar(100) not null unique
);

create table job_title(
    id int PRIMARY KEY generated by default as identity,
    name varchar(100) not null unique
);

create table authority_job_title(
    authority_id int references authority(id) on delete cascade,
    job_title_id int references job_title(id) on delete cascade,
    primary key (authority_id, job_title_id)
);

create table person(
    id int PRIMARY KEY generated by default as identity,
    name varchar(100) not null,
    system_role varchar(100) not null default ('ROLE_USER'),
    username varchar(100) not null unique,
    password varchar(100) not null,
    job_title_id int references job_title(id) on delete set null
);

create table pass_history(
    id int PRIMARY KEY generated by default as identity,
    person_id int references person(id) on delete cascade not null ,
    authority_id int references authority(id) on delete cascade not null ,
    date timestamp not null
);

insert into authority(name) values('Проходная');
insert into authority(name) values('Офис');
insert into authority(name) values('Серверная');
insert into job_title(name) values('Менеджер');
insert into job_title(name) values('Администратор');
insert into authority_job_title(authority_id, job_title_id) values(1, 1);
insert into authority_job_title(authority_id, job_title_id) values(1, 2);
insert into authority_job_title(authority_id, job_title_id) values(2, 1);
insert into authority_job_title(authority_id, job_title_id) values(3, 2);
insert into person(name, job_title_id, password, username) values('Иванов Иван Иванович', 1, '$2a$10$7BdEq7Vmf98p5q1qFfLsWucFs4aa3WmbslrkAudorwdLOwFbfUEre', 'Test');
insert into person(name, job_title_id, password, username) values('Администратор', 2, '$2a$10$7BdEq7Vmf98p5q1qFfLsWucFs4aa3WmbslrkAudorwdLOwFbfUEre', 'admin');